#!/bin/zsh
#
# FileName:     RUN
# Author:       8ucchiman
# CreatedDate:  2024-06-03 11:30:33
# LastModified: 2024-06-03 13:00:27
# Reference:    8ucchiman.jp
# Description:  ---
#

# Function to log messages to a file
function log_message () {
    local log_file="$1"
    shift
    local message="$*"
    local timestamp=$(date +"%Y-%m-%d %H:%M:%S")
    echo "${timestamp} - ${message}" tee -a "${log_file}"
}

# Function to log environment information
function log_env_info () {
    local log_file="$1"
    local mem_total=$(awk '/MemTotal/ {print $2}' /proc/meminfo)

    {
        echo "OS: $(uname -s) $(uname -r)"
        echo "CPU: $(uname -p)"
        echo "Memory: $((mem_total / 1024 / 1024)) GB"
        echo "Process ID: $$"
        echo "Running start time: $(date +"%Y-%m-%d %H:%M:%S")"
    } | tee -a "${log_file}"
}

# Function to log CPU/GPU occupancy
function log_occupancy () {
    local log_file="$1"
    local cpu_count=$(nproc)
    {
        echo "CPU Count: ${cpu_count}"
        echo "CPU Occupancy: $(top -bn1 | awk 'NR>7{s+=$9} END {print s}') %"
    } | tee -a "${log_file}"

    
    if command -v nvidia-smi &> /dev/null; then
        gpu_count=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
        # Loop through each GPU and get the required information
        for ((i=0; i<$gpu_count; i++)); do
            # Get GPU name, total memory, used memory, and free memory
            gpu_info=$(nvidia-smi --query-gpu=name,memory.total,memory.used --format=csv,noheader,nounits --id=$i)
            name=$(echo $gpu_info | cut -d',' -f1)
            total=$(echo $gpu_info | cut -d',' -f2)
            used=$(echo $gpu_info | cut -d',' -f3)

            # Calculate occupancy percentage
            occupancy=$(awk "BEGIN {printf \"%.2f\", $used / $total * 100}")

            {
                echo "ID: $i GPU($name), Total memory[$total MiB]"
                echo "    $used MiB / $total MiB ($occupancy % occupancy)"
            } | tee -a "${log_file}"


        done
        # Get CUDA version
        cuda_version=$(nvcc --version | grep -o "release [0-9.]*" | awk '{print $2}')
        echo "CUDA Version: $cuda_version" | tee -a "${log_file}"
    fi
}



function main () {
    # Main script
    log_dir="/tmp/logs"
    current_date=`date "+%Y_%m_%d_%H_%M_%S"`
    log_file="${log_dir}/${current_date}.log"


    mkdir -p "${log_dir}"
    touch "${log_file}"

    log_env_info "${log_file}"
    log_occupancy "${log_file}"
    if [[ $@ != "" ]]; then
    log_message "${log_file}" "Command:" "$@"
    # Run the command and log its output
    "$@" 2>&1 | tee -a "${log_file}"
    fi

    # Log end time
    echo "Running end time: $(date +"%Y-%m-%d %H:%M:%S")" | tee -a "${log_file}"
}

# eval $@
main $@
