#!/bin/zsh
#
# FileName:     Bmain
# Author:       8ucchiman
# CreatedDate:  2023-10-28 17:30:24
# LastModified: 2024-02-01 21:57:00
# Reference:    8ucchiman.jp
# Description:  ---
#





function pass () {
    #
    # @Description  pass function
    # @params       
    # @Example
    # @Reference    
    #

    
}

source ./Bmods 2>/dev/null || source $HOME/Bmods
main $@

return
