#!/bin/zsh
#
# FileName:     Bmain
# Author:       8ucchiman
# CreatedDate:  2023-10-28 17:30:24
# LastModified: 2023-12-15 15:00:30
# Reference:    8ucchiman.jp
# Description:  ---
#





function pass () {
    #
    # @Description  pass function
    # @params       
    # @Example
    # @Reference    
    #

    
}

source ./Bmods
main $@

return
