#!/bin/zsh
#
# FileName:     local
# Author:       8ucchiman
# CreatedDate:  2023-11-12 20:51:23
# LastModified: 2023-01-23 14:11:45 +0900
# Reference:    8ucchiman.jp
# Description:  ---
#


source $HOME/Bmods

function lopen () {
    echo "open"
}

function lbuild () {
    echo "build"
}

function lrun () {
    echo "run"
}

function lclean () {
    echo "clean"
}


eval $@
